[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dexaggregator = "8Gieuu4fEtwDM4Ztm6rGsaRrXZ7nTGdwZZR9xg8VqFrR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
